### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [fatchur/Face_demography#1]
Can you share the dataset?

**Comment by fatchur** [comment]
wait for a month.
I still prepare it.

if you are in a hurry, you can download it from eth zurich

**Comment by fatchur** [comment]
But if you download directly from eth zurich, you should sort it by your self. I use several days to sort it cause so many teenager faces classified as 50-60 years old.

**Comment by Zumbalamambo** [comment]
okay thank you
